# Generated by Django 5.2.9 on 2025-12-24 15:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelPriceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fuel_type', models.CharField(choices=[('GASOLINE', 'Gasolina'), ('ETHANOL', 'Etanol'), ('DIESEL', 'Diesel')], max_length=20, verbose_name='Tipo de Combustível')),
                ('price_per_liter', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Preço por Litro')),
                ('collected_at', models.DateTimeField(verbose_name='Data da Coleta')),
                ('source', models.CharField(choices=[('last_transaction', 'Última Transação'), ('manual', 'Manual'), ('external_anp', 'ANP')], default='last_transaction', max_length=30, verbose_name='Fonte')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_snapshots', to='core.fuelstation', verbose_name='Posto')),
            ],
            options={
                'verbose_name': 'Snapshot de Preço',
                'verbose_name_plural': 'Snapshots de Preço',
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['fuel_type', '-collected_at'], name='fuel_fuelpr_fuel_ty_dbbf5b_idx'), models.Index(fields=['fuel_type', 'station', '-collected_at'], name='fuel_fuelpr_fuel_ty_7d797b_idx')],
            },
        ),
        migrations.CreateModel(
            name='FuelTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchased_at', models.DateTimeField(verbose_name='Data/Hora do Abastecimento')),
                ('liters', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Litros')),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Preço por Litro')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('odometer_km', models.PositiveIntegerField(verbose_name='Odômetro (km)')),
                ('fuel_type', models.CharField(choices=[('GASOLINE', 'Gasolina'), ('ETHANOL', 'Etanol'), ('DIESEL', 'Diesel')], default='GASOLINE', max_length=20, verbose_name='Tipo de Combustível')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='fuel_transactions/%Y/%m/', verbose_name='Comprovante')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_transactions', to='core.costcenter', verbose_name='Centro de Custo')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_transactions', to='core.driver', verbose_name='Motorista')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_transactions', to='core.fuelstation', verbose_name='Posto')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_transactions', to='core.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Abastecimento',
                'verbose_name_plural': 'Abastecimentos',
                'ordering': ['-purchased_at'],
                'indexes': [models.Index(fields=['vehicle', '-purchased_at'], name='fuel_fueltr_vehicle_110707_idx'), models.Index(fields=['purchased_at'], name='fuel_fueltr_purchas_aa7c52_idx')],
            },
        ),
    ]
