# Generated by Django 5.2.9 on 2025-12-25 04:03

from django.db import migrations, models
from django.db.models import Count


def cleanup_duplicate_snapshots(apps, schema_editor):
    FuelPriceSnapshot = apps.get_model('fuel', 'FuelPriceSnapshot')
    duplicates = (
        FuelPriceSnapshot.objects.values('fuel_type', 'station_id')
        .annotate(cnt=Count('id'))
        .filter(cnt__gt=1)
    )

    for row in duplicates:
        qs = FuelPriceSnapshot.objects.filter(
            fuel_type=row['fuel_type'],
            station_id=row['station_id'],
        ).order_by('-collected_at', '-created_at', '-id')
        keep = qs.first()
        if keep:
            qs.exclude(id=keep.id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(cleanup_duplicate_snapshots, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='fuelpricesnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('station__isnull', True)), fields=('fuel_type',), name='uniq_fuel_price_global'),
        ),
        migrations.AddConstraint(
            model_name='fuelpricesnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('station__isnull', False)), fields=('fuel_type', 'station'), name='uniq_fuel_price_station'),
        ),
    ]
