# Generated by Codex on 2025-xx-xx

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0002_fuelpricesnapshot_uniq_fuel_price_global_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fuelpricesnapshot',
            name='uniq_fuel_price_global',
        ),
        migrations.RemoveConstraint(
            model_name='fuelpricesnapshot',
            name='uniq_fuel_price_station',
        ),
        migrations.AddConstraint(
            model_name='fuelpricesnapshot',
            constraint=models.UniqueConstraint(
                fields=('fuel_type', 'source'),
                condition=Q(station__isnull=True),
                name='uniq_fuel_price_global_source',
            ),
        ),
        migrations.AddConstraint(
            model_name='fuelpricesnapshot',
            constraint=models.UniqueConstraint(
                fields=('fuel_type', 'station', 'source'),
                condition=Q(station__isnull=False),
                name='uniq_fuel_price_station_source',
            ),
        ),
    ]
