# Generated by Django 5.2.9 on 2025-12-24 15:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('ODOMETER_REGRESSION', 'Regressão de Odômetro'), ('LITERS_OVER_TANK', 'Litros Acima da Capacidade'), ('OUTLIER_CONSUMPTION', 'Consumo Anômalo'), ('PERSONAL_USAGE', 'Uso Pessoal')], max_length=30, verbose_name='Tipo')),
                ('severity', models.CharField(choices=[('INFO', 'Informação'), ('WARN', 'Aviso'), ('CRITICAL', 'Crítico')], default='WARN', max_length=10, verbose_name='Severidade')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('fuel_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='fuel.fueltransaction', verbose_name='Abastecimento')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vehicle', '-created_at'], name='alerts_aler_vehicle_f10df0_idx'), models.Index(fields=['type', '-created_at'], name='alerts_aler_type_bd08d8_idx'), models.Index(fields=['resolved_at'], name='alerts_aler_resolve_08ce04_idx')],
            },
        ),
    ]
