# Generated by Django 5.2.9 on 2025-12-24 15:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('category', models.CharField(choices=[('RURAL', 'Rural'), ('URBAN', 'Urbano'), ('INSTALLATION', 'Instalação'), ('MAINTENANCE', 'Manutenção'), ('ADMIN', 'Administrativo')], default='URBAN', max_length=20, verbose_name='Categoria')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Centro de Custo',
                'verbose_name_plural': 'Centros de Custo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('doc_id', models.CharField(blank=True, max_length=20, verbose_name='CPF/RG')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Endereço')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Posto',
                'verbose_name_plural': 'Postos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plate', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('fuel_type', models.CharField(choices=[('GASOLINE', 'Gasolina'), ('ETHANOL', 'Etanol'), ('DIESEL', 'Diesel')], default='GASOLINE', max_length=20, verbose_name='Tipo de Combustível')),
                ('tank_capacity_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Capacidade do Tanque (L)')),
                ('usage_category', models.CharField(choices=[('OPERATIONAL', 'Operacional'), ('PERSONAL', 'Pessoal')], default='OPERATIONAL', max_length=20, verbose_name='Categoria de Uso')),
                ('min_expected_km_per_liter', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Consumo Mínimo Esperado (km/L)')),
                ('max_expected_km_per_liter', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Consumo Máximo Esperado (km/L)')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['name'],
            },
        ),
    ]
