# Generated by Django 5.2.8 on 2025-12-26 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_user_to_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='current_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_drivers', to='core.vehicle', verbose_name='Veículo Atual'),
        ),
    ]
