# Generated by Django 5.2.8 on 2025-12-26 00:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_current_vehicle_to_driver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data/Hora')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='Nome do Usuário')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('action', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Alteração'), ('DELETE', 'Exclusão')], db_index=True, max_length=10, verbose_name='Ação')),
                ('entity_type', models.CharField(db_index=True, max_length=100, verbose_name='Tipo de Entidade')),
                ('entity_id', models.CharField(max_length=100, verbose_name='ID da Entidade')),
                ('entity_description', models.CharField(blank=True, max_length=300, verbose_name='Descrição')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name='Dados Anteriores')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='Dados Novos')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='Alterações')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='core_auditl_entity__244637_idx'), models.Index(fields=['user', 'timestamp'], name='core_auditl_user_id_7b678c_idx')],
            },
        ),
    ]
